export const onBoardingTopics:any[] = [
  {
    id: "reduce-stress",
    title: "Reduce Stress",
    bgColor: "#808AFF",
    textColor: "#EBEAEC",
    height: 210,
    image: null,
  },
  {
    id: "Improve-Performance",
    title: "Improve Performance",
    bgColor: "#FA6E5A",
    textColor:"#FEF9F3",
    height: 167,
    image:null,
  },
  {
    id: "Increase-Happiness",
    title: "Increase Happiness",
    bgColor: "#F4A17C",
    textColor:"#3F414E",
    height: 167,
    image:null,
  },
  {
    id: "reduce-anxiety",
    title: "Reduce Anxiety",
    bgColor: "#FFCF86",
    textColor:"#3F414E",
    height: 210,
    image:null,
  },
  {
    id: "personnal-growth",
    title: "Personal Growth",
    bgColor: "#6CB28E",
    textColor:"#3F414E",
    height: 210,
    image:null,
  },
  {
    id: "Better-sleep",
    title: "Better Sleep",
    bgColor: "#4E5567",
    textColor:"#3F414E",
    height: 167,
    image:null,
  },
];
