export const onBoardingTopics: any[] = [
  {
    id: "reduce-stress",
    title: "Réduire le stress",
    bgColor: "#808AFF",
    textColor: "#EBEAEC",
    height: 210,
    image: require("../../assets/reduceStress.png"),
  },
  {
    id: "Improve-Performance",
    title: "Améliorer ses performances",
    bgColor: "#FA6E5A",
    textColor: "#FEF9F3",
    height: 167,
    image: require("../../assets/improvePerformance.png"),
  },
  {
    id: "Increase-Happiness",
    title: "Augmenter le bonheur",
    bgColor: "#F4A17C",
    textColor: "#3F414E",
    height: 167,
    image: require("../../assets/increaseHappiness.png"),
  },
  {
    id: "reduce-anxiety",
    title: "Réduire l'anxiété",
    bgColor: "#FFCF86",
    textColor: "#3F414E",
    height: 210,
    image: require("../../assets/reduceAnxiety.png"),
  },
  {
    id: "personnal-growth",
    title: "Développement personnel",
    bgColor: "#6CB28E",
    textColor: "#3F414E",
    height: 210,
    image: require("../../assets/personalGroup.png"),
  },
  {
    id: "Better-sleep",
    title: "Mieux dormir",
    bgColor: "#4E5567",
    textColor: "#3F414E",
    height: 167,
    image: require("../../assets/BetterSleep.png"),
  },
];
